#!/bin/bash 

#if OPENSHMEM is set to 1 
export OPENSHMEM_HOME=/opt/mvapich2-x/gnu
# if OPENSHMEM is set to 0
export MPI_HOME=/usr/local/mpi
export CUDA_HOME=/usr/local/cuda

#toggle trace generation functionality
export TRACING=0
export BLOCKLEVEL_TRACING=1 

#idea is to assume a zero latency, infinite bandwidth network. however yet to find a way to retain synchronization
export IDEALIZE=0

#use OpenSHMEM instead of MPI as the underlying CPU-CPU communication transport
export OPENSHMEM=0
